### ISSUE TITLE
'write_bed' crashes ruthlessly when path is not normalized or folder does not exist

### ISSUE THREAD

**Issue by richelbilderbeek** [OchoaLab/genio#6]
Dear genio maintainers,

Thanks for genio, I enjoy the package very much!

With this Issue I demonstrate when `write_bed` crashes ruthlessly and needlessly and suggest how to fix it in multiple ways.

This is how the crash looks like:

![Screenshot from 2021-09-20 11-23-39](https://user-images.githubusercontent.com/2098230/133981798-329e1f7d-8849-484f-a424-70ca72469725.png)

The cause is the use of un-normalized Linux paths, such as `~/my_folder`, where `~` is a shorthand notation for the Linux home folder, e.g `/home/my_username`.

I will demonstrate at the bottom of this Isse:

  1. `write_bed` works as expected, from documentation example code
  2. `write_bed` works as expected, when saving in a normalized path in a sub-folder that is created
  3. `write_bed` crashes ruthlessly, when saving in a normalized path in a sub-folder that does not exist
  4. `write_bed` crashes ruthlessly, when saving in an un-normalized path in a sub-folder that does exist

Here, I suggest two solutions:

 * `genio` normalizes the path and creates the folder needed, as done in example 2
 * `genio` gives nice error messages

I hope this Issue helps making `genio` even better!

Cheers, Richel Bilderbeek

```r
################################################################################
#
# 1. `write_bed` works as expected, from documentation example code
#
################################################################################
file_out <- tempfile('delete-me-example', fileext = '.bed') # will also work without extension
X <- rbinom(10, 2, 0.5)
X[sample(10, 3)] <- NA
X <- matrix(X, nrow = 5, ncol = 2)
genio::write_bed(file_out, X) # WORKS

################################################################################
#
# 2. `write_bed` works as expected, when saving 
#   * in a normalized path 
#   * in a sub-folder that exists
#
################################################################################
file_out <- file.path(
  rappdirs::user_cache_dir(appname = "my_r_package_name"),
  "sub_folder_2", "my_filename"
)
dir.create(dirname(file_out), recursive = TRUE)
file_out <- normalizePath(file_out, mustWork = FALSE)
#
# On my computer: 
# file_out == "/home/richel/.cache/my_r_package_name/sub_folder/my_filename"
#
X <- rbinom(10, 2, 0.5)
X[sample(10, 3)] <- NA
X <- matrix(X, nrow = 5, ncol = 2)
genio::write_bed(file_out, X) # WORKS

################################################################################
#
# 3. `write_bed` crashes ruthlessly, when saving 
#   * in a normalized path 
#   * in a sub-folder that does not exist
#
################################################################################
file_out <- file.path(
  rappdirs::user_cache_dir(appname = "my_r_package_name"),
  "sub_folder_3", "my_filename"
)
file_out <- normalizePath(file_out, mustWork = FALSE)
#
# On my computer: 
# file_out == "/home/richel/.cache/my_r_package_name/sub_folder/my_filename"
#
X <- rbinom(10, 2, 0.5)
X[sample(10, 3)] <- NA
X <- matrix(X, nrow = 5, ncol = 2)
genio::write_bed(file_out, X) # CAUSES ABORT

################################################################################
#
# 4. `write_bed` crashes ruthlessly, when saving 
#   * in an un-normalized path 
#   * in a sub-folder that does exist
#
################################################################################
file_out <- file.path(
  rappdirs::user_cache_dir(appname = "my_r_package_name"),
  "sub_folder_4", "my_filename"
)
dir.create(dirname(file_out), recursive = TRUE)
testthat::expect_equal(file_out, "~/.cache/my_r_package_name/sub_folder_4/my_filename")
X <- rbinom(10, 2, 0.5)
X[sample(10, 3)] <- NA
X <- matrix(X, nrow = 5, ncol = 2)
genio::write_bed(file_out, X) # CAUSES ABORT
```

**Comment by alexviiia** [comment]
Hi Richel,

Thanks again for your bug report with reproducible examples!  Sorry for delaying so much to solve.  I believe these issues are fixed but wanted to add details:

1. Opted for still causing an error if the output directory does not exist, as opposed to creating the directory automatically.  This follows what other writer functions do elsewhere (i.e. readr::read_tsv errors in this case too, and in general I'm not familiar with any that automatically create missing directories).  I like this too as it can help catch bugs rather than write files in unexpected locations.  However, now the error is in R rather than C++ so it shouldn't crash ruthlessly.
2. I wasn't able to reproduce the second problem (following your exact example, my code did not crash ruthlessly for an un-normalized path in a subfolder that does exist).  My latest code already normalized the path inside, maybe the report predates that change.

Please install the latest github version and reset the environment, retest on your end and let me know if you are still experiencing ruthless crashes.  Thanks!!!

**Comment by richelbilderbeek** [comment]
Confirmed to work locally:

![Screenshot from 2022-02-04 11-05-43](https://user-images.githubusercontent.com/2098230/152510530-443b309a-1535-4e29-8c44-8c793dcdd309.png)

**Comment by richelbilderbeek** [comment]
Also confirmed that it works now on GitHub Actions at [https://github.com/richelbilderbeek/genio/actions/runs/1794319381](https://github.com/richelbilderbeek/genio/actions/runs/1794319381)

**Comment by richelbilderbeek** [comment]
Hi @alexviiia, I can happily confirm this works. Thanks!
