### ISSUE TITLE
Suggest: create 'sample' data with a different number of SNPs and samples

### ISSUE THREAD

**Issue by richelbilderbeek** [OchoaLab/genio#8]
Dear genio maintainers.

Thanks for `genio`! I enjoy using it.

Since [the last update](https://github.com/OchoaLab/genio/commit/f4ef6a925d26f5813db6593e11c3bb3902ad28f5) however, my code breaks. That I can fix and this is not what this Issue is about.

What would help me if the `sample.bed`/`sample.bim`/`sample.fam` files would have a different number of SNPs and samples. Currently, there are 10 SNPs and 10 samples. In that way one can detect an error when one accidentally mixes up columns and rows.

Would be awesome and useful to me!

**Comment by alexviiia** [comment]
Regarding the 1.1.0.9000 update, not sure if it was clear that all I did was swap the bim$ref and bim$alt columns (see NEWS).  The original version was just wrong, I feel bad changing things but it'll be worth it in the long term.

As for the sample files, plink does this and that's what I did to generate the sample genotypes and other internal test data, see lines 5-21 of this script:

https://github.com/OchoaLab/genio/blob/master/tests/testthat/make_plink_examples.bash

And the several small bed/bim/fam files with unequal dimensions I generated with that script are found in that directory:

https://github.com/OchoaLab/genio/tree/master/tests/testthat

Let me know if these files, or the strategy for creating them, suffices for you, or what features are missing from it that are important to you.  Is it important that the package sample data have this property, or will these off-package files do?  (Note I did have concerns about odd dimensions in my internal tests, but the sample data was not created for the purpose of testing and I'm comfortable with it staying that way, proper testing requires looking at numerous edge cases and I don't like the idea of exporting sample data for all of those edge cases, polluting the environment.)

**Comment by richelbilderbeek** [comment]
Hi @alexviiia, thanks for your reply. 

>  if it was clear that all I did was swap the bim$ref and bim$alt columns (see NEWS). The original version was just wrong, I feel bad changing things but it'll be worth it in the long term.

It was clear; I was misreading at first here :blush: . I am happy too you did that change :-)

> Let me know if these files, or the strategy for creating them, suffices for you, or what features are missing from it that are important to you. Is it important that the package sample data have this property, or will these off-package files do?

Great that the asymmetric .bed files are in the testthat folder, that will suffice for me!

Thanks and keep up the good work :+1:
